import Head from "next/head";
import styled from "styled-components";
import Logo from "../../public/gummy-location.svg";
import Link from "next/link";

export default function Home() {
  return (
    <AppBody>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageWrapper>
        <AppLogo src={Logo.src} alt="logo" />
        <AppTitle>
          Map<span>Box</span>
        </AppTitle>

        <Link href="/welcomepage">
          <RoundButton>Get Started</RoundButton>
        </Link>

        <DevCredit>
          Develop by <a href="#">Haris Khan</a>
        </DevCredit>
      </PageWrapper>
    </AppBody>
  );
}

const AppBody = styled.div`
  position: relative;
  height: 100vh;
`;

const PageWrapper = styled.div`
  height: 100%;
  padding: 30px 25px;
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;

  &:before {
    content: "";
    position: absolute;
    background-image: url(Meteor.svg);
    background-size: cover;
    inset: 0;
    opacity: 0.65;
    z-index: -1;
  }
`;

const AppLogo = styled.img`
  max-width: 300px;
`;

const AppTitle = styled.h1`
  margin-top: -40px;
  font-size: 54px;
  font-weight: 700;
  line-height: 96px;
  color: #fff;
  text-transform: uppercase;

  span {
    color: #65cffd;
  }
`;

const RoundButton = styled.button`
  margin: 40px 0;
  padding: 12px 40px;
  background: linear-gradient(0deg, #438ef0, #438ef0),
    linear-gradient(0deg, #279cf1, #279cf1),
    linear-gradient(0deg, #1aa8ef, #1aa8ef),
    linear-gradient(0deg, #2cd3eb, #2cb3eb), #48bde5;
  box-shadow: 6px 6px 12px rgba(0, 0, 0, 0.6);
  border-radius: 50px;
  border: none;

  font-size: 24px;
  font-weight: 500;
  line-height: 36px;
  text-transform: uppercase;
  color: #fff;
  cursor: pointer;
  transition: 0.3s all;

  &:hover {
    transform: scale(1.1);
  }
`;

const DevCredit = styled.div`
  font-size: 18px;
  line-height: 27px;
  font-weight: normal;
  color: #fff;

  position: absolute;
  left: 0;
  right: 0;
  bottom: 20px;
  margin: 0 auto;

  a {
    color: #fcff70;
  }
`;
